// Column contracts mirrored from the SQL RPCs and the .xlsx templates
// generated by scripts/generate-bulk-templates.mjs. The frontend wizard uses
// these to validate that the user uploaded a file built from the right
// template (header row must match exactly, in order).

import type { BulkEntity } from "@/types/domain";

// 'usuarios' is handled via the BulkUsersModal (no Excel template), so it is
// excluded from the template-driven wizard surface.
export type TemplateEntity = Exclude<BulkEntity, "usuarios">;

export interface TemplateSchema {
  entity: TemplateEntity;
  title: string;
  templateUrl: string;
  columns: readonly string[];
  booleanColumns?: readonly string[];
}

export const TEMPLATE_SCHEMAS: Record<TemplateEntity, TemplateSchema> = {
  empresas: {
    entity: "empresas",
    title: "Empresas",
    templateUrl: "/templates/empresas.xlsx",
    columns: ["name", "phone", "email", "address", "logo_url"],
  },
  sucursales: {
    entity: "sucursales",
    title: "Sucursales",
    templateUrl: "/templates/sucursales.xlsx",
    columns: ["empresa", "name", "phone", "email", "address", "active"],
    booleanColumns: ["active"],
  },
  clientes: {
    entity: "clientes",
    title: "Clientes",
    templateUrl: "/templates/clientes.xlsx",
    columns: [
      "empresa",
      "sucursal",
      "name",
      "phone",
      "email",
      "address",
      "position",
      "photo_url",
    ],
  },
};

// Normalize the variety of boolean encodings users might put in the
// "active" column. Empty → undefined so the server picks its default.
export function parseBoolean(raw: unknown): boolean | undefined {
  if (raw === undefined || raw === null) return undefined;
  if (typeof raw === "boolean") return raw;
  const text = String(raw).trim().toLowerCase();
  if (text === "") return undefined;
  if (["si", "sí", "yes", "true", "1", "verdadero", "x"].includes(text)) return true;
  if (["no", "false", "0", "falso"].includes(text)) return false;
  return undefined;
}
